config/routes.rb
Rails.application.routes.draw do
  root "recipes#index"
  devise_for :users
  resources :recipes

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :recipes
end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
  has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  DIFFICULTY = %w(Easy Medium Hard)
  
  belongs_to :food_type
  belongs_to :food_preference
  belongs_to :cuisine
  
  validates :title, presence: true
  validates :food_preference_id, :food_type_id, :cuisine_id, presence: true
  
  scope :food_type, ->(food_type) { where food_type: food_type }
  scope :food_preference, ->(food_preference) { where food_preference: food_preference }
  scope :cuisine, ->(cuisine) { where cuisine: cuisine}
  scope :starts_with, ->(name) { where("title like ?", "#{name}%") }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :edit, :destroy, :create, :update]
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
    @recipes = @recipes.food_type(params[:food_types]) if params[:food_types].present? && params[:food_types] != "0"
    @recipes = @recipes.food_preference(params[:food_preferences]) if params[:food_preferences].present? && params[:food_preferences] != "0"
    @recipes = @recipes.cuisine(params[:cuisines]) if params[:cuisines].present? && params[:cuisines] != "0"
    @recipes = @recipes.starts_with(params[:search]) if params[:search].present?
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :difficulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_values
    @food_preferences = FoodPreference.all
    @food_types = FoodType.all
    @cuisines = Cuisine.all
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CurryNation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Static navbar -->
	<div class="row">
		<div class="navbar navbar-static-top">
			<div class="container">
				<button type="button", class="navbar-toggle",
				 data-toggle="collapse", data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand", href="#">
					<%= image_tag "logo.jpg" %>
				</a>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><%= link_to "Recipes", recipes_path %></li>
					</ul>
					<ul class="nav navbar-nav pull-right">
						<% if user_signed_in? %>
							<li><%= link_to "#{current_user.email}" %></li>
							<li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
						<% else %>
							<li><%= link_to "Login", new_user_session_path %></li>
							<li class="active"><%= link_to "SignUp", new_user_registration_path %></li>
						<% end %>
					</ul>
				</div>
				
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-2">
			<% sidebar_values %>
			
			<%= form_for(:recipes, method: :get) do |f| %>
				<div class="panel panel-primary" id="panels">
					<div class="panel-heading">Food Preferences</div>
					<div class="input-group">
						<% selected = params[:food_preferences] == "0" || (!params[:food_preferences].present?) %>
						<%= radio_button_tag 'food_preferences', '0', selected %>
						All
					</div>
					<% @food_preferences.each do |fp| %>
						<div class="input-group">
							<% selected = params[:food_preferences] == "#{fp.id}" %>
							<%= radio_button_tag 'food_preferences', fp.id, selected %>
							<%= fp.name %>
						</div>
					<% end %>
					
					<div class="panel-heading">Food Types</div>
					<div class="input-group">
						<% selected = (params[:food_types] == "0") || (!params[:food_types].present?) %>
						<%= radio_button_tag 'food_types', '0', selected %>
						All
					</div>
					<% @food_types.each do |ft| %>
						<div class="input-group">
							<% selected = params[:food_types] == "#{ft.id}" %>
							<%= radio_button_tag 'food_types', ft.id, selected %>
							<%= ft.name %>
						</div>
					<% end %>
					
					<div class="panel-heading">Cuisines</div>
					<div class="input-group">
						<% selected = params[:cuisines] == "0" || (!params[:cuisines].present?) %>
						<%= radio_button_tag 'cuisines', '0', selected %>
						All
					</div>	
					<% @cuisines.each do |c| %>
						<div class="input-group">
							<% selected = params[:cuisines] == "#{c.id}" %>
							<%= radio_button_tag 'cuisines', c.id, selected %>
							<%= c.name %>
						</div>
					<% end %>
				</div>
				<%= f.submit "Filter", class: "btn btn-default" %>
			<% end %>
		</div>
		<div class="col-lg-9">
			<div class="row">
				<div class="col-lg-8"></div>
				<div class="col-lg-4">
					<%= form_for(:recipes, method: :get) do |f| %>
						<div class="input-group">
							<%= text_field_tag 'search', nil, placeholder: "Search", class: "form-control" %>
							<span class="input-group-btn">
								<%= f.submit "Search", class: "btn btn-default" %>
							</span>
						</div>
					<% end %>
				</div>
			</div>
			
			<% if notice %>
				<p class="notice"><%= notice %></p>
			<% end %>
			
			<% if alert %>
				<p class="alert"><%= alert %></p>
			<% end %>
			
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <% @recipe.errors.full_messages.each do |message| %>
        <div class="alert alert-danger" role="alert">
        	<p><%= message %></p>
        </div>
      <% end %>
    </div>
  <% end %>
<div class="col-lg-6">
  <div class="input-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
  </div>
  <div class="input-group">
    <%= f.label :cooking_time %><br>
    <%= f.text_field :cooking_time, class: "form-control", placeholder: "Cooking time" %>
  </div>
  <div class="form-group">
    <%= f.label :difficulty_level %><br>
    <%= f.select :difficulty_level, Recipe::DIFFICULTY, {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :food_type %><br>
    <%= f.select(:food_type_id,
    		options_from_collection_for_select(FoodType.all, :id, :name),
    		{ prompt: "Please Choose" }, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :food_preference %><br>
    <%= f.select(:food_preference_id,
    		options_from_collection_for_select(FoodPreference.all, :id, :name),
    		{ prompt: 'Please Choose'}, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :cuisine %><br>
    <%= f.select(:cuisine_id,
    		options_from_collection_for_select(Cuisine.all, :id, :name),
    		{ prompt: 'Please Choose' }, class: "form-control") %>
  </div>
  <div class="input-group">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients, class: "form-control", placeholder: "Ingredients" %>
  </div>
  <div class="input-group">
    <%= f.label :procedure %><br>
    <%= f.text_area :procedure, class: "form-control", placeholder: "Procedure" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default"%>
  </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Cooking time</th>
      <th>Difficulty level</th>
      <th>Food type</th>
      <th>Food preference</th>
      <th>Cuisine</th>
      <th>Ingredients</th>
      <th>Procedure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% if @recipes %>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.cooking_time %></td>
        <td><%= recipe.difficulty_level %></td>
        <td><%= recipe.food_type.name %></td>
        <td><%= recipe.food_preference.name %></td>
        <td><%= recipe.cuisine.name %></td>
        <td><%= recipe.ingredients %></td>
        <td><%= recipe.procedure %></td>
        <td><%= link_to 'Show', recipe, class: "btn btn-primary btn-small" %></td>
        <% if user_signed_in? %>
	        <td><%= link_to 'Edit', edit_recipe_path(recipe), class: "btn btn-success btn-small" %></td>
	        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' },
	        		class: "btn btn-danger btn-small" %></td>
      	<% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recipe.title %>
</p>

<p>
  <strong>Cooking time:</strong>
  <%= @recipe.cooking_time %>
</p>

<p>
  <strong>Difficulty level:</strong>
  <%= @recipe.difficulty_level %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @recipe.food_type.name %>
</p>

<p>
  <strong>Food preference:</strong>
  <%= @recipe.food_preference.name %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @recipe.cuisine.name %>
</p>

<p>
  <strong>Ingredients:</strong>
  <%= @recipe.ingredients %>
</p>

<p>
  <strong>Procedure:</strong>
  <%= @recipe.procedure %>
</p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>